import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:intl/intl.dart';
import 'package:uuid/uuid.dart';
import '../cubits/subscription_cubit.dart';
import '../models/subscription.dart';

class AddSubscriptionPage extends StatefulWidget {
  final Subscription? subscription;

  const AddSubscriptionPage({super.key, this.subscription});

  @override
  State<AddSubscriptionPage> createState() => _AddSubscriptionPageState();
}

class _AddSubscriptionPageState extends State<AddSubscriptionPage> {
  final _formKey = GlobalKey<FormState>();
  late TextEditingController _nameController;
  late TextEditingController _priceController;
  late TextEditingController _freeTrialController;

  late SubscriptionPeriod _selectedPeriod;
  late DateTime _selectedDate;
  String _selectedCategory = 'Lainnya';
  final List<String> _categories = [
    'Musik',
    'Movie',
    'Work',
    'Disatukan',
    'Lainnya',
  ]; // Added 'Disatukan' (Bundle) or keep simple? 'Musik', 'Movie', 'Work', 'Lainnya'

  bool _remind7Days = false;
  bool _remind1Day = false;

  @override
  void initState() {
    super.initState();
    final sub = widget.subscription;
    _nameController = TextEditingController(text: sub?.name ?? '');
    // If price is 0.0 (default empty?), show empty
    _priceController = TextEditingController(
      text: sub != null ? sub.price.toStringAsFixed(0) : '',
    );
    _freeTrialController = TextEditingController(
      text: sub != null ? sub.freeTrialDays.toString() : '',
    );

    _selectedPeriod = sub?.period ?? SubscriptionPeriod.monthly;
    _selectedDate = sub?.firstBillDate ?? DateTime.now();
    _selectedCategory = sub?.category ?? 'Lainnya';

    if (_categories.contains(_selectedCategory) == false) {
      // Handle case if category not in list (legacy data or custom)
      if (!_categories.contains('Lainnya')) _categories.add('Lainnya');
      _selectedCategory = 'Lainnya';
    }

    if (sub != null) {
      _remind7Days = sub.reminders.contains(7);
      _remind1Day = sub.reminders.contains(1);
    }
  }

  @override
  void dispose() {
    _nameController.dispose();
    _priceController.dispose();
    _freeTrialController.dispose();
    super.dispose();
  }

  Future<void> _pickDate() async {
    final picked = await showDatePicker(
      context: context,
      initialDate: _selectedDate,
      firstDate: DateTime(2000),
      lastDate: DateTime(2100),
    );
    if (picked != null) {
      setState(() {
        _selectedDate = picked;
      });
    }
  }

  void _save() {
    if (_formKey.currentState!.validate()) {
      final name = _nameController.text;
      final price = double.tryParse(_priceController.text) ?? 0.0;
      final freeTrialDays = int.tryParse(_freeTrialController.text) ?? 0;

      final reminders = <int>[];
      if (_remind7Days) reminders.add(7);
      if (_remind1Day) reminders.add(1);

      // If we have an existing sub, we keep its ID. Otherwise, ID is generated by model/cubit logic.
      // But we changed model to have empty ID by default in const constructor.
      // So let's handle it here or in Cubit.

      final isEditing = widget.subscription != null;
      final idToUse = isEditing ? widget.subscription!.id : const Uuid().v4();

      final subscription = Subscription(
        id: idToUse,
        name: name,
        price: price,
        period: _selectedPeriod,
        firstBillDate: _selectedDate,
        reminders: reminders,
        category: _selectedCategory,
        freeTrialDays: freeTrialDays,
      );

      if (isEditing) {
        context.read<SubscriptionCubit>().updateSubscription(subscription);
      } else {
        context.read<SubscriptionCubit>().addSubscription(subscription);
      }
      Navigator.pop(context);
    }
  }

  @override
  Widget build(BuildContext context) {
    final isEditing = widget.subscription != null;

    return Scaffold(
      backgroundColor: Colors.grey[100],
      appBar: AppBar(
        title: Text(
          isEditing ? 'Ubah Langganan' : 'Buat Langganan Baru',
          style: GoogleFonts.poppins(fontWeight: FontWeight.w600),
        ),
        centerTitle: true,
        elevation: 0,
        backgroundColor: Colors.transparent,
        foregroundColor: Colors.black,
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(24.0),
        child: Form(
          key: _formKey,
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              _buildLabel('Nama Layanan'),
              TextFormField(
                controller: _nameController,
                decoration: _inputDecoration('Contoh: Netflix, Spotify'),
                validator: (v) =>
                    v == null || v.isEmpty ? 'Masukkan nama' : null,
              ),
              const SizedBox(height: 20),

              _buildLabel('Harga'),
              TextFormField(
                controller: _priceController,
                keyboardType: TextInputType.number,
                decoration: _inputDecoration('Contoh Rp50000', prefix: 'Rp '),
                validator: (v) =>
                    v == null || v.isEmpty ? 'Masukkan harga' : null,
              ),
              const SizedBox(height: 20),

              _buildLabel('Kategori'),
              DropdownButtonFormField<String>(
                value: _selectedCategory,
                decoration: _inputDecoration(''),
                items: _categories.map((c) {
                  return DropdownMenuItem(value: c, child: Text(c));
                }).toList(),
                onChanged: (v) {
                  if (v != null) setState(() => _selectedCategory = v);
                },
              ),
              const SizedBox(height: 20),

              Row(
                children: [
                  Expanded(
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        _buildLabel('Jenis Periode'),
                        DropdownButtonFormField<SubscriptionPeriod>(
                          initialValue: _selectedPeriod,
                          decoration: _inputDecoration(''),
                          items: SubscriptionPeriod.values.map((p) {
                            return DropdownMenuItem(
                              value: p,
                              child: Text(switch (p) {
                                SubscriptionPeriod.weekly => 'Mingguan',
                                SubscriptionPeriod.monthly => 'Bulanan',
                                SubscriptionPeriod.quarterly => 'Kuartal',
                                SubscriptionPeriod.yearly => 'Tahunan',
                              }),
                            );
                          }).toList(),
                          onChanged: (v) {
                            if (v != null) setState(() => _selectedPeriod = v);
                          },
                        ),
                      ],
                    ),
                  ),
                  const SizedBox(width: 16),
                  Expanded(
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        _buildLabel('Tanggal Tagihan'),
                        InkWell(
                          onTap: _pickDate,
                          child: InputDecorator(
                            decoration: _inputDecoration(''),
                            child: Row(
                              mainAxisAlignment: MainAxisAlignment.spaceBetween,
                              children: [
                                Text(
                                  DateFormat(
                                    'dd MMM yyyy',
                                  ).format(_selectedDate),
                                ),
                                const Icon(Icons.calendar_today, size: 16),
                              ],
                            ),
                          ),
                        ),
                      ],
                    ),
                  ),
                ],
              ),
              Row(
                children: [
                  Expanded(
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        _buildLabel('Masa Percobaan (Hari)'),
                        TextFormField(
                          controller: _freeTrialController,
                          keyboardType: TextInputType.number,
                          decoration: _inputDecoration('0', prefix: ''),
                          validator: (v) {
                            if (v == null || v.isEmpty)
                              return null; // Optional, defaults to 0
                            if (int.tryParse(v) == null)
                              return 'Angka tidak valid';
                            return null;
                          },
                        ),
                      ],
                    ),
                  ),
                ],
              ),
              const SizedBox(height: 24),

              _buildLabel('Pengingat'),
              const SizedBox(height: 8),
              Container(
                padding: const EdgeInsets.all(12),
                decoration: BoxDecoration(
                  color: Colors.white,
                  borderRadius: BorderRadius.circular(12),
                  boxShadow: [
                    BoxShadow(
                      color: Colors.black.withValues(alpha: 0.05),
                      blurRadius: 10,
                      offset: const Offset(0, 4),
                    ),
                  ],
                ),
                child: Column(
                  children: [
                    SwitchListTile(
                      title: const Text('7 Hari Sebelum'),
                      value: _remind7Days,
                      activeThumbColor: Colors.deepPurple,
                      onChanged: (v) => setState(() => _remind7Days = v),
                    ),
                    const Divider(height: 1),
                    SwitchListTile(
                      title: const Text('1 Hari Sebelum'),
                      value: _remind1Day,
                      activeThumbColor: Colors.deepPurple,
                      onChanged: (v) => setState(() => _remind1Day = v),
                    ),
                  ],
                ),
              ),

              const SizedBox(height: 40),
              SizedBox(
                width: double.infinity,
                height: 54,
                child: ElevatedButton(
                  onPressed: _save,
                  style: ElevatedButton.styleFrom(
                    backgroundColor: Colors.deepPurple,
                    foregroundColor: Colors.white,
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(16),
                    ),
                    elevation: 4,
                  ),
                  child: Text(
                    isEditing ? 'Ubah Langganan' : 'Simpan Langganan',
                    style: GoogleFonts.poppins(
                      fontSize: 16,
                      fontWeight: FontWeight.w600,
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }

  Widget _buildLabel(String text) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 8.0),
      child: Text(
        text,
        style: GoogleFonts.poppins(
          fontSize: 14,
          fontWeight: FontWeight.w500,
          color: Colors.grey[700],
        ),
      ),
    );
  }

  InputDecoration _inputDecoration(String hint, {String? prefix}) {
    return InputDecoration(
      hintText: hint,
      prefixText: prefix,
      filled: true,
      fillColor: Colors.white,
      contentPadding: const EdgeInsets.symmetric(horizontal: 16, vertical: 16),
      border: OutlineInputBorder(
        borderRadius: BorderRadius.circular(12),
        borderSide: BorderSide.none,
      ),
      enabledBorder: OutlineInputBorder(
        borderRadius: BorderRadius.circular(12),
        borderSide: BorderSide.none,
      ),
      focusedBorder: OutlineInputBorder(
        borderRadius: BorderRadius.circular(12),
        borderSide: const BorderSide(color: Colors.deepPurple, width: 1.5),
      ),
    );
  }
}

extension StringExtension on String {
  String capitalize() {
    return "${this[0].toUpperCase()}${substring(1)}";
  }
}
